### ISSUE TITLE
The Token config Usage no display 😓

### ISSUE THREAD

**Issue by chinanf-boy** [kevinburke/travis#1]
I think the token config`{toml}` Usage is not just wirte on that code

I could not find the Usage of the token config on `readme.md`

> I have to look around the source code

#### 1. I run the first time then Error Log is 

``` bash
$ travis enable
Error getting token: read /Users/***/.travis: is a directory
``` 

> Sometime the https://github.com/travis-ci/travis.rb tool write the config with `yml` in `HOME/.travis/config.yml`

#### 2. after look the source code , I create the `config.toml` file in `HOME/.travis/config.toml`

> And I change some `rcFilename := filepath.Join(homeDir, ".travis/config.toml")` <== **add the config.toml**

https://github.com/kevinburke/travis/blob/master/lib/travis.go#L54

**Comment by kevinburke** [comment]
Gah, yikes. I forgot the default `travis` tool creates a directory named `.travis`, and should probably change the fallback to read from `.travisrc` instead.
